/* Builds site/content.js from the newest content/propositions.vN.json (or the one given as argv[2]),
   and site/figures.js from research/figures-*.json (merged), so the site has one source of truth. */
const fs = require('fs'), path = require('path');
const root = path.join(__dirname, '..');
const contentDir = path.join(root, 'content');
let file = process.argv[2];
if (!file) {
  const files = fs.readdirSync(contentDir).filter((f) => /^propositions\.v\d+\.json$/.test(f)).sort((a, b) => Number(a.match(/v(\d+)/)[1]) - Number(b.match(/v(\d+)/)[1]));
  file = path.join(contentDir, files[files.length - 1]);
}
const content = JSON.parse(fs.readFileSync(file, 'utf8'));
// Balance guard: each axis must have equal pull in both directions (±1 item, ±0.5 weight), or the wording can push people.
['danger', 'speed'].forEach((ax) => {
  const its = content.items.filter((it) => it.axis === ax);
  const up = its.filter((it) => it.dir === 1), dn = its.filter((it) => it.dir === -1);
  const w = (a) => a.reduce((s, it) => s + (it.weight || 1), 0);
  if (Math.abs(up.length - dn.length) > 1 || Math.abs(w(up) - w(dn)) > 0.5) { console.error(`BALANCE FAIL on ${ax}: +${up.length}/${w(up)} vs -${dn.length}/${w(dn)}`); process.exit(1); }
  console.log(`balance ${ax}: +${up.length} (${w(up)}) / -${dn.length} (${w(dn)})`);
});
fs.writeFileSync(path.join(root, 'site', 'content.js'), `/* generated from ${path.basename(file)} by tools/build-content.js */\nwindow.STL_CONTENT = ${JSON.stringify(content)};\n`);
const frFile = file.replace(/\.json$/, '.fr.json');
if (fs.existsSync(frFile)) {
  const fr = JSON.parse(fs.readFileSync(frFile, 'utf8'));
  const ids = content.items.map((i) => i.id).join(','), fids = fr.items.map((i) => i.id).join(',');
  if (ids !== fids) { console.error('FR translation item ids differ from EN:', fids); process.exit(1); }
  fr.items.forEach((it, i) => { const en = content.items[i]; it.axis = en.axis; it.dir = en.dir; it.weight = en.weight; it.type = en.type; it.sub = en.sub; });
  fs.writeFileSync(path.join(root, 'site', 'content.fr.js'), `/* generated from ${path.basename(frFile)} by tools/build-content.js */\nwindow.STL_CONTENT_FR = ${JSON.stringify(fr)};\n`);
  console.log('fr content:', fr.items.length, 'items');
} else {
  fs.writeFileSync(path.join(root, 'site', 'content.fr.js'), `/* no French content yet */\n`);
}
const resDir = path.join(root, 'research');
let figures = [];
if (fs.existsSync(resDir)) {
  fs.readdirSync(resDir).filter((f) => /^figures-.*\.json$/.test(f)).sort().forEach((f) => {
    try { const j = JSON.parse(fs.readFileSync(path.join(resDir, f), 'utf8')); (j.figures || []).forEach((fig) => { if (figures.some((x) => x.id === fig.id)) return; const ids = new Set(content.items.map((i) => i.id)); fig = Object.assign({}, fig, { predictions: Object.fromEntries(Object.entries(fig.predictions || {}).filter(([k]) => ids.has(k))) }); /* predictions for ids dropped from the content stay in research/ only */ figures.push(fig); }); }
    catch (e) { console.error('skip', f, e.message); }
  });
}
fs.writeFileSync(path.join(root, 'site', 'figures.js'), `/* generated by tools/build-content.js from research/figures-*.json */\nwindow.STL_FIGURES = ${JSON.stringify(figures)};\n`);
const crowdFile = path.join(root, 'site', 'crowd.js');
if (!fs.existsSync(crowdFile)) fs.writeFileSync(crowdFile, `/* crowd snapshot: {asOf, n, points:[[x,y],...]} — regenerated by tools/snapshot-crowd.js */\nwindow.STL_CROWD = { asOf: null, n: 0, points: [] };\n`);
console.log('content:', path.basename(file), content.items.length, 'items; figures:', figures.length);
